title Simple hangout where media set is overlapped with hair check
set autonumber true

participant Alice as Alice
participant Alice's Browser as A
participant Alice's App as App
participant Alice's Turn as Turn
participant Web Server Browse as Web
participant Media Switch as MCU
A <-> Web: Load Page 
App <-> Web: Authenticate
Web <-> MCU: stuff
Web -> App: Offer 
App -> Alice: Check Hair
App -> A: create PeerConnection()
A -> Turn: Alloc
App -> A: SetRemote( Offer ) 
App -> A: createAnswer(  Provisional )
Turn -> A: IPs and Ports
A -> App: answer 
prAns:App -> A: setLocal
A -> App: onRemoteStream main
A -> App: onRemoteStream thumbnail one
A -> App: onRemoteStream thumbnail two
A <-> MCU: ICE
prStuff: Web -> MCU: stuff
App@prAns -> Web@prStuff: answer 
A <-> MCU: DTLS
A <-> MCU: SRTP
Alice -> App: Hair is fluffy 
App -> A: addStream audio/video
App -> A: createAnswer
A -> App: answer
ans:App -> A: setLocal
stuff: Web -> MCU: stuff
App@ans -> Web@stuff: answer 
A <-> MCU: SRTP
