title Simple Call Flow
set autonumber true

participant Alice's Turn as TurnA
participant Alice's Browser as A
participant Alice's App as AppA
participant Alice as Alice
participant Alice's Web Server as WebA
participant Bob's Web Server as WebB
participant Bob as Bob
participant Bob's App as AppB
participant Bob's Browser as B
participant Bob's Turn as TurnB
A <-> WebA: Load Page 
A <-> WebA: Authenticate
AppA -> A: create PeerConnection()
A -> TurnA: Alloc
TurnA -> A: IPs and Ports
B <-> WebB: Load Page 
B <-> WebB: Authenticate
AppB -> B: create PeerConnection()
B -> TurnB: Alloc
TurnB -> B: IPs and Ports
Alice -> AppA: Call Bob 
AppA -> A: addStream( data )
AppA -> A: addStream( audio/video )
AppA -> A: createOffer
A -> AppA: offer
AppA -> A: setLocal
AppA -> WebA: Offer to Bob
WebA -> WebB: Offer to Bob
WebB -> AppB: Offer
AppB -> B: SetRemote 
B -> AppB: TBD Remote has audio, video, and data 
AppB -> Bob: Phones Ringing Dude
AppB -> B: addStream( data )
AppB -> B: createAnswer( Provisional, RelayOnly )
B -> AppB: PR_Answer
AppB -> B: setLocal
sendPrAns: AppB -> WebB: PR_Answer to Alice 
B@sendPrAns -> TurnB: Permission
B -> AppB: onRemoteStream( data )
B <-> TurnB: ICE Check
TurnB <-> A: ICE Check 
B <-> TurnB: DTLS
TurnB <-> A: DTLS
B <-> TurnB: SCTP/Data
TurnB <-> A: SCTP/Data
A -> AppA: onRemoteStream( data )
WebB@sendPrAns -> WebA: PR_Answer [duration=9]
WebA -> AppA: PR_Answer
AppA -> A: setRemote
A -> TurnA: Permission
Bob -> AppB: Accept Audio and Video 
AppB -> B: addStream( audio/video )
AppB -> B: createAnswer
B -> AppB: Answer 
AppB -> B: setLocal
sendAns:AppB -> WebB: Answer to Alice
B -> AppB: onRemoteStream( audio/video )
B <-> TurnB: RTP/Data
TurnB <-> A: RTP/Data
B <-> A: ICE Check
B <-> A: RTP/Data
WebB@sendAns -> WebA: Answer [duration=6]
WebA -> AppA: Answer
AppA -> A: setRemote 

