title Simple Call Flow
set autonumber true

participant Alice's Turn as TurnA
participant Alice's Browser as A
participant Alice's App as AppA
participant Alice as Alice
participant Alice's Web Server as WebA
participant Bob's Web Server as WebB
participant Bob as Bob
participant Bob's App as AppB
participant Bob's Browser as B
participant Bob's Turn as TurnB

A <-> WebA: Load Page 
A <-> WebA: Authenticate


B <-> WebB: Load Page 
B <-> WebB: Authenticate

Alice -> AppA: Call Bob 
AppA -> A: createPeerConnection()

AppA -> A: createDataStream
AppA -> A: getUserMedia( audio and video )
AppA -> A: addStream( audio/video )
AppA -> A: createOffer
A -> TurnA: Alloc
TurnA -> A: IPs and Ports
A -> AppA: callback createOffer( offer )
AppA -> A: setLocal
AppA -> WebA: Offer to Bob
WebA -> WebB: Offer to Bob
WebB -> AppB: Offer

AppB -> B: create PeerConnection()
AppB -> B: SetRemote 
B -> AppB: onaddstream( audio / video )
AppB -> Bob: Phones Ringing Dude
AppB -> B: createAnswer( Provisional, RelayOnly )
B -> TurnB: Alloc
TurnB -> B: IPs and Ports
B -> AppB: addTrack( audio )
B -> AppB: addTrack( video )
B -> AppB: callback createAnswer( PR_Answer )

AppB -> B: setLocal
sendPrAns: AppB -> WebB: PR_Answer to Alice 
B@sendPrAns -> TurnB: Permission

WebB@sendPrAns -> WebA: PR_Answer [duration=1]
WebA -> AppA: PR_Answer
AppA -> A: setRemote

A -> TurnA: Permission

B <-> TurnB: ICE Check
TurnB <-> A: ICE Check 
B <-> TurnB: DTLS
TurnB <-> A: DTLS
B <-> TurnB: SCTP/Data
TurnB <-> A: SCTP/Data
B -> AppB: ondatachannel

Bob -> AppB: Accept Audio and Video 
AppB -> B: getUserMedia( audio and video )
AppB -> B: addStream( audio/video )
AppB -> B: createAnswer

B -> AppB: Answer 
AppB -> B: setLocal
sendAns:AppB -> WebB: Answer to Alice


B <-> TurnB: SRTP
TurnB <-> A: SRTP 
B <-> A: ICE Check
B <-> A: SRTP without relay

WebB@sendAns -> WebA: Answer [duration=6]
WebA -> AppA: Answer
AppA -> A: setRemote 
A -> AppA: onaddstream( audio/video )
A -> AppA: addTrack( audio )
A -> AppA: addTrack( video )


Bob -> AppB: add document camera 
AppB -> B: getUserMedia 
AppB -> B: addStream
B -> AppB: onnegotationneeded
AppB -> B: createOffer
AppB -> B: setLocal 
AppB -> WebB: offer
WebB -> WebA: offer
WebA -> AppA: offer
AppA -> A: setRemote
A -> AppA: onaddstream( video )
AppA -> A: createAnswer
A -> AppA: addTrack( video )
AppA -> WebA: answer
WebA -> WebB: answer
WebB -> AppB: answer
AppB -> B: setRemote 
B -> AppB: addTrack( video )

